### ISSUE TITLE
Can't create a datasource using metatrone engine

### ISSUE THREAD

**Issue by hashansl** [metatron-app/metatron-discovery#1760] opened 2019-03-27 10:54 UTC
I'm getting " Name is Null " error. Why is this ? How can I solve this ? 
![Screenshot from 2019-03-27 06-47-17](https://user-images.githubusercontent.com/45277530/55070511-cee77780-505c-11e9-919a-fee28181fd52.png)

**Comment by i1befree** [comment] 2019-03-28 02:47
@hashansl Sorry. The test was delayed because I was on a business trip. I will test it today.

**Comment by hashansl** [comment] 2019-03-28 02:50
@i1befree Okay.. Thank you!

**Comment by alchan-lee** [comment] 2019-04-01 04:29
I've tested it and found a hole when importing a datasource directly from druid.
It is reproduced when a granularity is null (or NONE).

I'll fix it and it will be released into the coming version (maybe in this week).

If you want to use this feature faster, please checkout `f#1760-engine_granularity_nullcheck` branch and rebuild your application.

Thanks for your great contribution @hashansl.

**Closed** 2019-04-02 02:20 UTC
Labels: @datasource, bug
