### ISSUE TITLE
KPI Chart Number Formatting Function by Measure

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#3640] opened 2021-04-01 05:04 UTC
**Is your feature request related to a problem? Please describe.**
KPI Chart Number Formatting Function by Measure

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minhyun2** [comment] 2021-06-17 05:32
Duplicate of #3720

**Closed by minhyun2** 2021-06-17 05:32 UTC
Labels: @chart
