### ISSUE TITLE
Added detailed setting function for grid measurement value column

### ISSUE THREAD

**Issue by eltriny** [metatron-app/metatron-discovery#3606] opened 2021-02-25 01:04 UTC
**Is your feature request related to a problem? Please describe.**
There were many opinions that it was inconvenient to use because there is no setting for each column of the grid.

**Describe the solution you'd like**
When creating a chart, a function must be added so that you can set each column on the shelf.

**Comment by minhyun2** [comment] 2021-03-23 02:26
Duplicate of #3572

**Closed** 2021-03-23 02:30 UTC
Labels: @chart
