### ISSUE TITLE
Engine Access Error occurs when clicking each column on the Column Detail screen

### ISSUE THREAD

**Issue by Cazen** [metatron-app/metatron-discovery#510] opened 2018-10-22 00:04 UTC
**Describe the bug**
**It is difficult to reproduce this error in the azure development environment. This is because the datasource and column are project-dependent. I would like you to check the in-house network access to view the T-map project or request to me the necessary logs**
When I clicked on each column in the column detail screen, I was able to check Engine Access Error from time to time. I can not tell exactly what case in the datasource will be happened(most of the case are from measure values), but an example in a T-map environment is shown below.

sales.Discount
sales.Profit
sales.Sales
sales.SalesperCustomer
sales.SalesaboveTarget

**To Reproduce**
1. Go to workbook and click add dashboard
2. Click on add datasource and go to detail screen
3. Go to column detail tab right side of data grid
4. Clicking each column and engine access error occurred sometimes

**Expected behavior**
Error should not be shown(include Engine access error)

**Screenshots**
![2018-10-22 9 03 05](https://user-images.githubusercontent.com/10334774/47274002-55dd8300-d5d9-11e8-8f90-2c71fae32e12.png)

**Desktop (please complete the following information):**
 - Tmap Alpha Dashboard version

**Additional context**

**Comment by kyungtaak** [comment] 2018-11-11 12:44
@alchan-lee I'll assign this issue to you. Can you confirm that it will be reproduced?

**Comment by alchan-lee** [comment] 2018-11-26 08:02
It shown as related to unhappy druid's side.

I can not check whole specific error, because it is not depend on discovery side.

Fortunately, we fixed related issue into #710 
and I think our new version (> 3.0.7) would be resolve this issue by unload columns which has error.

**Closed by alchan-lee** 2018-11-26 08:02 UTC
Labels: @datasource, needs confirmation
