### ISSUE TITLE
where is binary/jar ?

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#840] opened 2018-11-21 12:58 UTC
https://metatron.app/index.php/download/installation-guide-custom-install/ mentions "you need to do is Download Metatron Binary (now 3.0.5 version is available)" but there is no jar inside the tarball on that link

**Comment by kyungtaak** [comment] 2018-11-23 12:40
sorry for the inconvenience caused by wrong link :( . I will prepare a real(!) link of druid binary for version 3.0.7 until next week.

**Comment by alchan-lee** [comment] 2018-11-26 06:41
@tooptoop4 
thank you for posting this point.

[This Link](https://sktmetatronkrsouthshared.blob.core.windows.net/metatron-public/discovery-dist/Discovery/3.0.7/metatron-discovery-3.0.7-bin.tar.gz)  is our newly (and stable) deployed binary.

I think we need to update website's infos fit our deploy schedules.
I close this issue, but if you have any queries you can keep discuss here freely.

**Closed by alchan-lee** 2018-11-26 06:41 UTC
Labels: question
